default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default

production:
  <<: *default
 host: dpg-ck2njturu70s738rt3fg-a
 database: s_original_3tto
 username: s_original_3tto_user
 password: 70M3TkFvAliOjIxdnWJHTxwfsYB5FZs3