default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default

production:
  <<: *default
host: dpg-ck2njturu70s738rt3fg-a
database: 5432
username: s_original_3tto
password: s_original_3tto_user